---
title: "Energy Price and Demand app"
author: "Group cdjs (Chris,David,Jaehee,Santiago)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Use Case


This app has been designed in order to analyze the demand as well as the price for energy inputs across different states. This app may be used by businesses and economists who may want to analyze the usage of different sources of energy as well as the price by different states. We know that for the manufacturing sector as well as other business sectors, a large fraction of costs pertain to energy alone and hence, this app uses data from the eia in order to provide those who want to make energy related business decisions with statistical and graphical information.   


## Who is the expected typical user? 

This app may be used by business analysts, economists, policymakers, or general public who may want to analyze the usage of different sources of energy as well as the price by different states. 
We know that for the manufacturing sector as well as the business sector, a large fraction of costs pertain to energy alone. Therefore, this app uses data from the EIA in order to provide those who want to make energy related business decisions, policymaking, or public understanding. This app will help improve the understanding of the interaction with the economy and environment.

## Typical questions that this app should help the user answer.


>>>>>>> 677de5201203db6a00bd8bbf7737318e60c7c7fc

# Required Packages

## What Packages to Download

The use of the app requires that the user must have the following packages installed:

## Description of the required packages
1. `eia`- eia provides API access to data from the US Energy Information Administraion
2. `shiny` - shiny helps to build interactive web applications with R
3. `tidyverse` -  tidyverse is an opinionated collection of R packages
4. `lubridate`- lubridate helps to make it easier to manipulate and parse dates.
5. `ggplot2` - ggplot2 helps to create graphics
6. `ggthemes` - ggthemes provides extra themes such as theme_bw()
7. `ggcorrplot` - ggcorrplot is a graphical display of a correlation matrix using ggplot2
8. `GGally`- GGally is an extension to ggplot2 and it includes pairwise plot matrix
9. `broom`- broom can convert statistical analysis objects from R into tidy tibbles
10. `shinythemes` - shinythemes helps to change the overall appearance of the Shiny application

## Version used in the app
1. `eia` - In order to run the app the use of version >=0.3.7 is suggested and >=0.1.0 is required.  
2. `shiny` - In order to run the app the use of version >= 1.0.0 is required.  
3. `tidyverse` - In order to run the app the use of version >= 3.3.3 is required.  
4. `lubridate` - In order to run the app the use of version >= 1.7.1 is suggested and >=1.7.0 is required.  
5. `ggplot2` - In order to run the app the use of version >= 3.0.0 is required.  
6. `ggthemes` - In order to run the app the use of version >= .  
7. `ggcorrplot` - In order to run the app the use of version >= 0.1.3 is suggested.  
8. `GGally` - In order to run the app the use of version >= . 
9. `broom` - In order to run the app the use of version >=0.3 is required. 
10. `shinythemes` - In order to run the app the use of version >=1.1.1.  


# Data Source and Structure

 

## Data Source 
Data was collected from Energy Information Administration(EIA) -> https://www.eia.gov/opendata/ 

Get access to EIA API query browser ->  https://www.eia.gov/opendata/qb.php

Five Data that is used in this app are: 

Electricity Price, Customers, Carbon Emissions, Total Electricity, Retail Sales.

In order to find each data fast, here is the guideline to find each data from the API query browser: 

 1. Electricity Price: EIA Data Sets -> Electricity -> Average retail price of electricity -> Industrial
 2. Customers: EIA Data Sets -> Electricity -> Number of customer accounts
 3. Carbon Emissions: EIA Data Sets -> CO2 Emissions -> by State
 4. Total Electricity: EIA Data Sets -> Electricity -> Net generation
 5. Retail Sales: EIA Data Sets -> Electricity -> Retail sales of electricity

Use eia package to have an API access to data from EIA 

There were yearly, monthly, quarterly for each data but this app only uses yearly data

## Data Structure



# EDA Inputs, Controls, and Outputs

## Overview
In order to perform EDA, the data needed to be cleaned. Given that two data frames were used, we give the scope for the user to make analysis from different perspectives. These data set along with the commands in the app allow the user to conduct an effective EDA that includes 6 different tabs of which 5 include graphical information and 4 are interactive. The tabs provide statistical and graphical information such as density plot, histogram, and a frequency polygon for single variable analysis. Linear model for two variable and tim-series analysis and a correlation heat map for the multivariate analysis.

## Tabs and EDA
The **univariate** tab allows the user to see the distribution for each of the variables. This allows the user to see how different energy sources or energy prices are distributed in each state. Also, this tab allows the user to choose between a frequency polygon, a histogram, and a density plot so the user may visualize the variables as preferred.

The **bivariate** tab allows the user to make comparisons between variables in the data set. That is, by allowing the user select variables of interest to display a linear regression model so that the user may make predictions based of the data. For example, the user may see that there is trend that carbon emissions are going up with time. The user may then switch to the bivariate tab in order to see how energy prices in that state correlate with an increase in carbon emissions. 

The **multivariate** tab allows the user to see simultaneous correlations between different variables of interest. This tab was added to provide the user with additional information regarding association between variables.

The **time-series** tab allows the user to see the fluctuations and trends for variables through time. This tab is meant to be complemented with bivariate tab in order to analyze a question of interest. This tab outputs a linear model with time on the x axis so that the user may see how energy prices, retail sales, carbon emissions vary with time and also, see how much that variable is estimated to change in the future. For example, a manufacturing business looking to open up next year may be interested in the trends and the predicted prices for electricity in order to save costs.


# Statistical Analysis Inputs, Controls, and Outputs


## Overview 
We provided statistical output in order to complement the graphical statistics. 



# Refrences

There are three references from either academic papers or widely available authoritative sources that are relevant to this app. See below: 


1. https://www.frbatlanta.org/-/media/documents/research/publications/economic-review/2006/vol91no3_dhawan-jeske.pdf

2. https://www.degruyter.com/document/doi/10.2202/1935-1690.1607/html

3. https://www.aeaweb.org/articles?id=10.1257/jel.46.4.871














