---
title: "Group Project"
author: "Christopher Hopkins"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(devtools)
# Install blsAPI Package
library(blsAPI) #BLS API
library(rjson)
# INstall eia Package
library(eia) #Energy API
library(lubridate)
```
*For bls data we will do 
Chris: 14 first states in alphabetical order.
Santiago: 14-32 states alphabetical order
Jaehee: 32-51 states...



```{r}
#BLS dataframe for unemployment rate in Alaska and Alabama
# Notes about ID the first two numbers are state and the letters at the start represent data set.
# Steps for finding ID: Go to this link for state numbers: https://download.bls.gov/pub/time.series/sm/sm.state
# Go to this link: https://beta.bls.gov/dataQuery/find?fq=survey:%5Bla%5D&s=popularity:D
# Copy the code for one state
# Change the first two numbers based on state code.
# Easiest way to do this is copy the code for one state
# state_list = state ID number
create_BLSID <- function (data_set_ID, state_list, rest){
  map2()

}


state_list <- c("02", "01")

#data<-list(seriesid = c("LAUST020000000000003", "LAUST010000000000003"))
data<-list(seriesid=create_BLSID("LAUST", state_list, "0000000000003"))
data
blsAPI(data , 2, TRUE)->test
test

#Example of how to clean BLS dataframe
test %>% 
  mutate(seriesID = case_when(
    str_detect(seriesID, "LAUST020000000000003") ~ "Alabama-Unemployment",
    str_detect(seriesID, "LAUST010000000000003") ~ "Alaska-Unemployment"
  )) %>% 
  separate(seriesID, c("State", "Type"), sep = "-") %>% 
  pivot_wider(names_from = "Type",
              values_from = "value")


#EIA dataframe 

eia_set_key("8a87a727635f5c834e2799cd76fcb820")
eia_data <- create_EIA_data(type, abrv, set)
eia_data
eia_series(eia_data)->df
df$data

#Example of how to clean EIA dataframe
state_names <- c("Alabama", "Alaska")

df %>% 
  select(data)->df

df %>% 
  mutate(data = map(df$data, ~.x %>% 
  mutate(
         month = month(month, label = TRUE))))->df

df %>% 
  mutate(data = Map(cbind, df$data, state=state_names))->df

df$data

```

```{r}

#Creating IDs EIA

eai_id <- tibble(start = c("ELEC.PRICE.", "TEST.PRICE."), abrv = list(c("AL", "AK", "MD", "DC")), end = c("-TEST1", "-TEST2"))

unnest(eai_id)->eai_id

eai_id %>% 
  mutate(id = str_c(start, abrv, end))->eai_id


#Creating IDs BLS

BLS_id <- tibble (start = c("LAUST", "TEST"), state = list(c("02", "01", "52", "32")), end = c("000000", "00000002"))

unnest(BLS_id)->BLS_id

BLS_id %>% 
  mutate(id = str_c(start, state, end))->BLS_id

BLS_id


```

