---
title: "Plan Assesment"
author: "Christopher Hopkins"
date: "4/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# App Title: 

### Team Members:

- Christopher Hopkins

- Santiago Nule

- Jaehee Lee

- David Willbourne

## Data Sources:

- U.S. Bureau of labor statistics, we will use their API: https://www.bls.gov/developers/

- U.S.Energy Information Administration,  we will use their API: https://www.eia.gov/opendata/

### Layout

We will be making a map of the united states in a main panel with a sidebar panel allowing the user to select at least two metrics, employment/unemployment and energy consumption/price . These metrics will then change the color of the map indicating relevant information, based on user selection.

### Data Analysis and Visulization with User Choices and Results

we will do a research along with a 
shiny app that helps visualize how labor demand varies around the US as 
energy inputs varies. We discussed on first focusing on the price of coal that
reflects electricity use and then see how firms readjust their labor. In order 
to see labor adjustments, we will look at the unemployment rate as well as 
labor income data. 

The visualization will be two U.S maps. The input will be a slider which will feature slider input animate so that the maps can react once the slider moves through time. The variables that will animate the map will be unemployment in one and energy prices on the other map. We want the user to see relations between input prices and labor demand.

### Team Member Responsibilities and Project Scheldue

1. Sprint one: (3/28/21 - 4/10/21)
  
  - David: Research and Research Questions
  
  - Santiago: Research and Research Questions
  
  - Christopher: API integration and Data Cleaning
  
  - Jaehlee: Data Cleaning and Statistical analysis

2. Sprint two: (4/11/21 - 4/28/21)

  - David: Front End, app design and layout
  
  - Santiago: Front End, app design and layout
  
  - Christopher: Statistical analysis and Graphing
  
  - Jaehlee: Statistical analysis and Graphing

Project Steps:

1. Research and Research Question identification

2. API 

3. Data selection and cleaning

4. Statistical analysis

5. Graphing, design and layout. 

