---
title: "map"
author: "santiago"
date: "4/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(usmap)
library(tidyverse)
```

```{r}
read_csv(file = "data/Full_data_4_26.csv")->full_data
read_rds("../../lectures_class/95_mapping/data/covid_data.rds")->df_all
```


```{r}

```


```{r}
plot_usmap(data = state_cases, values = Current_Total, color = "blue") + 
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Cases", label = scales::comma)+
  labs(title = "US States",
       subtitle = paste0("Total Cases by State as of ",
max(state_cases$Date))) + 
  theme(panel.background = element_rect(color = "black", fill = "white")) +
  theme(legend.position = "top")
```

```{r}
full_data %>% 
  rename(state = state_name) %>% 
  select(-c("abb", "month", "year", "unemployment_rate"))->testdata
  
plot_usmap( data = testdata, values = "avg_electricity", color = "blue") +
   scale_fill_continuous(low = "white", high = "red", 
                        name = "Cases per Capita", 
                        label = scales::comma)

```


```{r}

df_all %>% 
  filter(Date == max(Date)) %>% 
  rename(state_name = Province_State) %>% 
  full_join(y = full_data, by = "state_name") %>%
  rename( tfips= sFIPS) %>% 
  View()
  relocate(FIPS, avg_electricity) %>% 
  select(-c("iso2", "iso3", "UID", "County","Combined_Key", "Lat", "Long"))->hi

plot_usmap(include = state_name, data = hi, values = "avg_electricity", color = "blue")+
  scale_fill_continuous(low = "white", high = "red", 
                        name = "Cases", label = scales::comma)
  
```

